apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: echo-ingres
spec:
  rules:
  - host: {{ .Values.ingress.hosts[0].host }}
    http:
      paths:
      - path: {{ .Values.ingress.hosts[0].paths[0].path }}
        backend:
          service:
            name: echo-service
            port:
              number: {{ .Values.service.port }}